### ISSUE TITLE
Feature request: css modules, or an equivalent mechanism

### ISSUE THREAD

**Issue by Iceburgino** [futursolo/stylist-rs#106]
It's not even about modules themselves (as files) - it's about the fact that each class name gets mapped to a unique class name, and that makes the style local. It would be great to have something like `local_css!` macro that takes  String as an argument and returns a Map, which you can then use. Like this

```Rust
let some_style =  local_css! {
    "
    .some_class {
         property: value;
         property: value;
    }
    .some_other_class {
         property: value;
         property: value;
    }
    "
};
```

and then, in Yew:

```Rust
html! {
    <div class={some_style["some_class"]}>
        {"Styled text"}
    </div>
    <div class={some_style["some_other_class"]}>
         {"Differently styled text"}
     </div>
}
```

I know there is [modules-css](https://crates.io/crates/css-modules), but having this functionality in this crate would make it feature-complete. Besides, I see you have a `css!` macro which functions similarly to what I described. I don't know the actual complexity of implementing this, but I hope it's easy enough for you to consider.

**Comment by futursolo** [comment]
Thank you for the feature request.

I think you can already do:

```rust
let (some_class, some_other_class) = (
     css! {
         property: value;
         property: value;
    },
    css! {
         property: value;
         property: value;
    }
);
```

**Comment by Iceburgino** [comment]
@futursolo 

Yes, but that still doesn't provide you with the feature of separation of files you would have if you could name your classes yourself, and the macro could replace them with the generated class names for localizing the scope of styling. Like it would in react:

```jsx
import styles from './some_style.module.css';

function SomeComponent(props) {
   return <div className={styles.some_class}/>
}
```

in the DOM, `styles.some_class` in this case would be replaced with something-like `some_class__SGq7F` where the `__SGq7F` part would be added by react to make it local to the file it is being used in. I'm sure you can recreate something like this with `include!` or `include_str!` macro in Rust.

I've seen a similar thing with `css!` macro. Class names when using it look like 
```html
<button class="stylist-HuhJdxcD src/app.rs:17:15">Hellos styled button</button>
```

**Comment by futursolo** [comment]
With stylist, You can assign prefixes with the following method:

```rust
let (some_class, some_other_class) = (
     Style::create("some-class", css! {
         property: value;
         property: value;
    }).unwrap(),
    Style::create("some-other-class", css! {
         property: value;
         property: value;
    }).unwrap()
);
```

You can make a `macro_rules!` wrapper if you think above is too verbose.

**Comment by Iceburgino** [comment]
As I've mentioned before, this does not handle the case where you want to separate your style, with multiple classes in it, into a file, and then selectively apply styles from this file to your component. You are required to put all your styles into Rust code. `include!` won't help here since there is no need to separate a style of a single class into a file.

**Comment by futursolo** [comment]
Thank you for this proposal.

Whilst I feel it's possible to utilise the existing API to make it with procedural macros relatively easily by reusing the parser exposed by Stylist and emitting the result into a struct that exposes each top level individual class names as `Style` instances with fields, importing stylesheets from external files is out-of-scope for a CSS-in-Rust solution like Stylist.

I do not feel we should accept this into Stylist as a `local_css!` macro is less than ideal when processing inline stylesheets.

Assigning local class names shares the same philosophy as the now defunct `makeStyles` / `useStyles` API from Material UI v4 (now known as MUI).
IMHO, one of the reasons why this API failed to gain popularity is because it forced users to give additional class names where users can simply make more styles with `makeStyles`. So users started naming their classes `root`, `container`, which is not very useful in general and resulted in less than ideal experience with CSS-in-JS when comparing with styled components / emotion.

If you would like to make this as a different crate and is interested in using stylist for stylesheet parsing / processing, feel free to do so and I am happy to provide support with it.

**Comment by WorldSEnder** [comment]
> ```js
> import styles from './some_style.module.css';
> 
> function SomeComponent(props) {
>    return <div className={styles.some_class}/>
> }
> ```

This kind of processing is not feasible in rust proc macros, to my knowledge. Reading and modifying the contents of a file referred to by path is hard to do correctly in proc macros (i.e. rebuilding in watch mode and incremental caching should work without a separate build script). As such, I can't identify an approach where we could work with external file contents instead of string literals. Hope that changes in the future, but afaik, it cant be currently done.
