### ISSUE TITLE
Proposal: Allow prefixes

### ISSUE THREAD

**Issue by Madoshakalaka** [futursolo/stylist-rs#61]
It's a routine to adjust CSS rules in the browser's developer tools and edit them back in code.

I find it hard to locate where the code is with all the same looking `stylist-hash` class names.

<img width="314" alt="image" src="https://user-images.githubusercontent.com/44753941/147183139-ac4f25cb-1957-4ea9-92b3-d012935d2300.png">

I used to work with a @WorldSEnder branch a lot, where you can specify prefixes for the class names. I would prefix every class name with the component name and I enjoyed doing it so much:

<img width="196" alt="image" src="https://user-images.githubusercontent.com/44753941/147183344-bab4e0f2-c766-4162-a2bc-d9f0ca74dee4.png">

Can we have the option for stylist to prefix the names? That's would be so helpful for tweaking in development.

**Comment by futursolo** [comment]
Having a different class name means a style tag needs to be inserted. The performance impact can be big (can be 1000x slower than cached tags) so we cannot have this in production mode.

It might be handy to have this in dev mode through.

**Comment by WorldSEnder** [comment]
Note that it is possible to provide a prefix on an per-app basis by using a `ManagerProvider`. *Do not insert them all over your application, performance will degrade heavily.*

```jsx
<stylist::yew::ManagerProvider manager={..your configured manager with prefix}>
    <App />
</stylist::yew::ManagerProvider>
```

To my understanding you want to tweak this on a per-component-basis? Here indeed, the performance trade-off is to be able to reuse the same style sheet, the prefix shouldn't matter. Note the "naive" middle ground of giving the prefix as a hint but only using it when such a style doesn't already exist would be even worse, because the prefix would then be misleading.

@futursolo perhaps we can make the `Into<Classes>: Style` impl emit multiple classes, one binding the style sheet and one that identifies the place where the `Style` was instantiated?
